# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - records-explorer/**
      - records-explorer.Tests/**
      - net-recap.sln
  pull_request:
    branches: [ "main" ]
    paths:
      - records-explorer/**
      - records-explorer.Tests/**
      - net-recap.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore records-explorer/
    - name: Build
      run: dotnet build --no-restore records-explorer/
    - name: Test
      run: dotnet test --no-build --verbosity normal records-explorer/
