name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - src/**/*
      - net-recap.sln
      - .github/workflows/*
  pull_request:
    branches: [ "main" ]
    paths:
      - src/**/*
      - net-recap.sln
      - .github/workflows/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: dotnet build net-recap.sln
